apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atrium.fullname" . }}-config
data:
  ATRIUM_LOG_LEVEL: "INFO"
  ATRIUM_SANDBOX_BACKEND: "{{ .Values.sandbox.backend }}"
  ATRIUM_SANDBOX_NAMESPACE: "{{ .Values.sandbox.namespace }}"
  ATRIUM_SANDBOX_STORAGE_CLASS: "{{ .Values.sandbox.storageClass }}"
